/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './templates/**/*.html.twig',
        './src/**/*.js',
        './src/**/*.twig',
        './src/**/*.php',
        './quitpath.theme',
        './quitpath.info.yml',
        './quitpath.libraries.yml'
    ],
    theme: {
        extend: {},
    },
    plugins: [],
    safelist: [
    'list-disc',
    'pl-6',
    'pl-8',
    'pl-10',
    'lg:gap-40',
    'to-green-200',
    'to-red-100',
    'to-blue-100',
    'to-blue-50',
    'to-yellow-100',
    'to-yellow-200',
    'to-yellow-300',
    'bg-green-100',
    'bg-green-200',
    'bg-green-300',
    'bg-green-600',
    'bg-green-400',
    'bg-red-50',
    'bg-red-100',
    'bg-red-200',
    'bg-red-300',
    'bg-red-400',
    'bg-red-600',
    'bg-blue-50',
    'bg-blue-100',
    'bg-blue-200',
    'bg-blue-300',
    'bg-blue-800',
    'bg-light-blue-50',
    'bg-light-blue-100',
    'bg-light-blue-200',
    'bg-light-blue-300',
    'bg-yellow-50',
    'bg-yellow-100',
    'bg-yellow-200',
    'bg-yellow-300',
    'bottom-12',
    '-bottom-17',
    '-bottom-6',
    '-bottom-25'
  ]
}